if [ ! "$(type oh-my-posh)" ]; then
  curl -s https://ohmyposh.dev/install.sh | bash -s
fi
eval "$(oh-my-posh init zsh --config ~/.config/ohmyposh/zen.yaml)"

export PATH=$PATH:$HOME/.cargo/bin

ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"

# download zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "${ZINIT_HOME}/zinit.zsh"
